/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lucas
 */
public class ViewClienteDesktop extends javax.swing.JFrame {

    /**
     * Creates new form ViewClienteDesktop
     */
    public ViewClienteDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopCliente = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnClDesktopFile = new javax.swing.JMenu();
        MnClDesktopSair = new javax.swing.JMenuItem();
        MnClDesktopNavegador = new javax.swing.JMenu();
        MnClDesktopAlterar = new javax.swing.JMenuItem();
        MnClDesktopDeletar = new javax.swing.JMenuItem();
        MnClDesktopProduto = new javax.swing.JMenu();
        MnClDesktopCarrinho = new javax.swing.JMenuItem();
        MnClDesktopPesquisar = new javax.swing.JMenuItem();
        MnClDesktopSobre = new javax.swing.JMenu();
        MnClDesktopLoja = new javax.swing.JMenuItem();
        MnClDesktopCriadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopCliente.setPreferredSize(new java.awt.Dimension(1500, 1000));

        javax.swing.GroupLayout DesktopClienteLayout = new javax.swing.GroupLayout(DesktopCliente);
        DesktopCliente.setLayout(DesktopClienteLayout);
        DesktopClienteLayout.setHorizontalGroup(
            DesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        DesktopClienteLayout.setVerticalGroup(
            DesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        MnClDesktopFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-icon.png"))); // NOI18N
        MnClDesktopFile.setText("Arquivo");

        MnClDesktopSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MnClDesktopSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit-icon.png"))); // NOI18N
        MnClDesktopSair.setText("Sair");
        MnClDesktopSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClDesktopSairActionPerformed(evt);
            }
        });
        MnClDesktopFile.add(MnClDesktopSair);

        jMenuBar1.add(MnClDesktopFile);

        MnClDesktopNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-icon.png"))); // NOI18N
        MnClDesktopNavegador.setText("Cliente");

        MnClDesktopAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/person-edit-icon.png"))); // NOI18N
        MnClDesktopAlterar.setText("Alterar Cadastro");
        MnClDesktopAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClDesktopAlterarActionPerformed(evt);
            }
        });
        MnClDesktopNavegador.add(MnClDesktopAlterar);

        MnClDesktopDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/person-delete-icon.png"))); // NOI18N
        MnClDesktopDeletar.setText("Deletar Cadastro");
        MnClDesktopDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClDesktopDeletarActionPerformed(evt);
            }
        });
        MnClDesktopNavegador.add(MnClDesktopDeletar);

        jMenuBar1.add(MnClDesktopNavegador);

        MnClDesktopProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto-icon.png"))); // NOI18N
        MnClDesktopProduto.setText("Produto");

        MnClDesktopCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho-icon.png"))); // NOI18N
        MnClDesktopCarrinho.setText("Meu Carrinho");
        MnClDesktopCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClDesktopCarrinhoActionPerformed(evt);
            }
        });
        MnClDesktopProduto.add(MnClDesktopCarrinho);

        MnClDesktopPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar-icon.png"))); // NOI18N
        MnClDesktopPesquisar.setText("Pesquisar Produto");
        MnClDesktopProduto.add(MnClDesktopPesquisar);

        jMenuBar1.add(MnClDesktopProduto);

        MnClDesktopSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/info-icon.png"))); // NOI18N
        MnClDesktopSobre.setText("Sobre");

        MnClDesktopLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loja-icon.png"))); // NOI18N
        MnClDesktopLoja.setText("Sobre a Loja");
        MnClDesktopSobre.add(MnClDesktopLoja);

        MnClDesktopCriadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/team-icon.png"))); // NOI18N
        MnClDesktopCriadores.setText("Sobre os Criadores");
        MnClDesktopCriadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClDesktopCriadoresActionPerformed(evt);
            }
        });
        MnClDesktopSobre.add(MnClDesktopCriadores);

        jMenuBar1.add(MnClDesktopSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnClDesktopSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClDesktopSairActionPerformed
        ViewClienteDesktop.this.dispose(); 
    }//GEN-LAST:event_MnClDesktopSairActionPerformed

    private void MnClDesktopAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClDesktopAlterarActionPerformed
        ViewClienteAlterar viewClienteAltera = new ViewClienteAlterar();
        DesktopCliente.add(viewClienteAltera);
        viewClienteAltera.setVisible(true);
    }//GEN-LAST:event_MnClDesktopAlterarActionPerformed

    private void MnClDesktopDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClDesktopDeletarActionPerformed
        ViewClienteDeletar viewClienteDeletar = new ViewClienteDeletar();
        DesktopCliente.add(viewClienteDeletar);
        viewClienteDeletar.setVisible(true);
    }//GEN-LAST:event_MnClDesktopDeletarActionPerformed

    private void MnClDesktopCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClDesktopCarrinhoActionPerformed
        ViewMeuCarrinho viewMeuCarrinho = new ViewMeuCarrinho();
        DesktopCliente.add(viewMeuCarrinho);
        viewMeuCarrinho.setVisible(true);
    }//GEN-LAST:event_MnClDesktopCarrinhoActionPerformed

    private void MnClDesktopCriadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClDesktopCriadoresActionPerformed
        new ViewCriadores().setVisible(true);
    }//GEN-LAST:event_MnClDesktopCriadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewClienteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewClienteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewClienteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewClienteDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewClienteDesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopCliente;
    private javax.swing.JMenuItem MnClDesktopAlterar;
    private javax.swing.JMenuItem MnClDesktopCarrinho;
    private javax.swing.JMenuItem MnClDesktopCriadores;
    private javax.swing.JMenuItem MnClDesktopDeletar;
    private javax.swing.JMenu MnClDesktopFile;
    private javax.swing.JMenuItem MnClDesktopLoja;
    private javax.swing.JMenu MnClDesktopNavegador;
    private javax.swing.JMenuItem MnClDesktopPesquisar;
    private javax.swing.JMenu MnClDesktopProduto;
    private javax.swing.JMenuItem MnClDesktopSair;
    private javax.swing.JMenu MnClDesktopSobre;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
