/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class ViewFuncionarioCadastra extends javax.swing.JDialog {

    /**
     * Creates new form ViewFuncionarioCadastraD
     */
    public ViewFuncionarioCadastra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSexoFnCadastro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFnCadastroNome = new javax.swing.JTextField();
        txtFnCadastroEmail = new javax.swing.JTextField();
        txtFnCadastroTelefone = new javax.swing.JFormattedTextField();
        txtFnCadastroCpf = new javax.swing.JFormattedTextField();
        SexoMasculino = new javax.swing.JRadioButton();
        SexoFeminino = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnFnCadastroCancelar = new javax.swing.JButton();
        btnFnCadastroSalvar = new javax.swing.JButton();
        txtFnCadastroLogin = new javax.swing.JTextField();
        txtFnCadastroSenha = new javax.swing.JPasswordField();
        txtFnCadastroConfSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFnCadastroCargo = new javax.swing.JTextField();
        txtFnCadastroSalario = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnFnCadastroFile = new javax.swing.JMenu();
        MnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro - Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setText("Nome *:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Cpf *:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Sexo *:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Email *:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Telefone *:");

        txtFnCadastroNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroNomeFocusLost(evt);
            }
        });

        txtFnCadastroEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroEmailFocusLost(evt);
            }
        });
        txtFnCadastroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnCadastroEmailActionPerformed(evt);
            }
        });

        try {
            txtFnCadastroTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFnCadastroTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroTelefoneFocusLost(evt);
            }
        });

        try {
            txtFnCadastroCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFnCadastroCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroCpfFocusLost(evt);
            }
        });

        GrupoSexoFnCadastro.add(SexoMasculino);
        SexoMasculino.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SexoMasculino.setText("Masculino");

        GrupoSexoFnCadastro.add(SexoFeminino);
        SexoFeminino.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SexoFeminino.setText("Feminino");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Login *:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Senha *:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setText("Confirmar Senha *:");

        btnFnCadastroCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFnCadastroCancelar.setText("Cancelar");
        btnFnCadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCadastroCancelarActionPerformed(evt);
            }
        });

        btnFnCadastroSalvar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnFnCadastroSalvar.setText("Salvar");
        btnFnCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCadastroSalvarActionPerformed(evt);
            }
        });

        txtFnCadastroLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroLoginFocusLost(evt);
            }
        });

        txtFnCadastroSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroSenhaFocusLost(evt);
            }
        });

        txtFnCadastroConfSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFnCadastroConfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroConfSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroConfSenhaFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("Cargo *:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setText("Sálario *:");

        txtFnCadastroCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroCargoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroCargoFocusLost(evt);
            }
        });

        txtFnCadastroSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        txtFnCadastroSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnCadastroSalarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnCadastroSalarioFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnFnCadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFnCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFnCadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFnCadastroConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFnCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFnCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFnCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFnCadastroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFnCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(SexoMasculino)
                            .addGap(43, 43, 43)
                            .addComponent(SexoFeminino)))
                    .addComponent(txtFnCadastroCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFnCadastroSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFnCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFnCadastroCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SexoMasculino)
                    .addComponent(SexoFeminino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFnCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFnCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFnCadastroCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFnCadastroSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFnCadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFnCadastroSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFnCadastroConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFnCadastroCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnCadastroSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo-icon.png"))); // NOI18N

        MnFnCadastroFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-icon.png"))); // NOI18N
        MnFnCadastroFile.setText("Arquivo");

        MnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit-icon.png"))); // NOI18N
        MnSair.setText("Sair");
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        MnFnCadastroFile.add(MnSair);

        jMenuBar1.add(MnFnCadastroFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnCadastroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnCadastroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnCadastroEmailActionPerformed

    private void btnFnCadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCadastroCancelarActionPerformed
        txtFnCadastroNome.setText("");
        txtFnCadastroNome.setBackground(Color.white);
        
        txtFnCadastroCpf.setText("");
        txtFnCadastroCpf.setBackground(Color.white);
        
        GrupoSexoFnCadastro.clearSelection();
        
        txtFnCadastroEmail.setText("");
        txtFnCadastroEmail.setBackground(Color.white);
        
        txtFnCadastroTelefone.setText("");
        txtFnCadastroTelefone.setBackground(Color.white);
        
        txtFnCadastroCargo.setText("");
        txtFnCadastroCargo.setBackground(Color.white);
        
        txtFnCadastroSalario.setText("");
        txtFnCadastroSalario.setBackground(Color.white);
        
        txtFnCadastroLogin.setText("");
        txtFnCadastroLogin.setBackground(Color.white);
        
        txtFnCadastroSenha.setText("");
        txtFnCadastroSenha.setBackground(Color.white);
        
        txtFnCadastroConfSenha.setText("");
        txtFnCadastroConfSenha.setBackground(Color.white);        
    }//GEN-LAST:event_btnFnCadastroCancelarActionPerformed

    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
        ViewFuncionarioCadastra.this.dispose();
    }//GEN-LAST:event_MnSairActionPerformed

    private void btnFnCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCadastroSalvarActionPerformed
        try{
            if("".equals(txtFnCadastroNome.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Nome' em Branco");            
            }
            if("".equals(txtFnCadastroCpf.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'CPF' em Branco");            
            }
            if("".equals(txtFnCadastroEmail.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Email' em Branco");            
            }
            if("".equals(txtFnCadastroTelefone.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Telefone' em Branco");            
            }      
            if("".equals(txtFnCadastroCargo.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Cargo' em Branco");            
            }
            if("".equals(txtFnCadastroSalario.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Salario' em Branco");            
            }
            if("".equals(txtFnCadastroLogin.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Login' em Branco");            
            }
            if("".equals(txtFnCadastroSenha.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Senha' em Branco");            
            }
            if("".equals(txtFnCadastroConfSenha.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Confirmar Senha' em Branco");            
            }
            
            if (!txtFnCadastroSenha.getText().equals(txtFnCadastroConfSenha.getText())) {
                JOptionPane.showMessageDialog(this, "Campo 'Senha' e 'Confirmar Senha' não são iguais");
                txtFnCadastroSenha.setBackground(Color.red);
                txtFnCadastroConfSenha.setBackground(Color.red);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro no Cadastro, por favor verificar todos os campos");
        }

    }//GEN-LAST:event_btnFnCadastroSalvarActionPerformed

    private void txtFnCadastroNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroNomeFocusGained
        txtFnCadastroNome.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroNomeFocusGained

    private void txtFnCadastroNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroNomeFocusLost
        if(txtFnCadastroNome.getText().trim().equals("")) {
        txtFnCadastroNome.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroNomeFocusLost

    private void txtFnCadastroCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroCpfFocusGained
        txtFnCadastroCpf.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroCpfFocusGained

    private void txtFnCadastroCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroCpfFocusLost
        if(txtFnCadastroCpf.getText().trim().equals("")) {
        txtFnCadastroCpf.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroCpfFocusLost

    private void txtFnCadastroEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroEmailFocusGained
        txtFnCadastroEmail.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroEmailFocusGained

    private void txtFnCadastroEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroEmailFocusLost
        if(txtFnCadastroEmail.getText().trim().equals("")) {
        txtFnCadastroEmail.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroEmailFocusLost

    private void txtFnCadastroTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroTelefoneFocusGained
        txtFnCadastroTelefone.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroTelefoneFocusGained

    private void txtFnCadastroTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroTelefoneFocusLost
        if(txtFnCadastroTelefone.getText().trim().equals("")) {
        txtFnCadastroTelefone.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroTelefoneFocusLost

    private void txtFnCadastroCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroCargoFocusGained
        txtFnCadastroCargo.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroCargoFocusGained

    private void txtFnCadastroCargoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroCargoFocusLost
        if(txtFnCadastroCargo.getText().trim().equals("")) {
        txtFnCadastroCargo.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroCargoFocusLost

    private void txtFnCadastroSalarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroSalarioFocusGained
        txtFnCadastroSalario.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroSalarioFocusGained

    private void txtFnCadastroSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroSalarioFocusLost
        if(txtFnCadastroSalario.getText().trim().equals("")) {
        txtFnCadastroSalario.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroSalarioFocusLost

    private void txtFnCadastroLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroLoginFocusGained
        txtFnCadastroLogin.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroLoginFocusGained

    private void txtFnCadastroLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroLoginFocusLost
        if(txtFnCadastroLogin.getText().trim().equals("")) {
        txtFnCadastroLogin.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroLoginFocusLost

    private void txtFnCadastroSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroSenhaFocusGained
        txtFnCadastroSenha.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroSenhaFocusGained

    private void txtFnCadastroSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroSenhaFocusLost
        if(txtFnCadastroSenha.getText().trim().equals("")) {
        txtFnCadastroSenha.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroSenhaFocusLost

    private void txtFnCadastroConfSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroConfSenhaFocusGained
        txtFnCadastroConfSenha.setBackground(Color.white);
    }//GEN-LAST:event_txtFnCadastroConfSenhaFocusGained

    private void txtFnCadastroConfSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnCadastroConfSenhaFocusLost
        if(txtFnCadastroConfSenha.getText().trim().equals("")) {
        txtFnCadastroConfSenha.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtFnCadastroConfSenhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioCadastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioCadastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioCadastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionarioCadastra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewFuncionarioCadastra dialog = new ViewFuncionarioCadastra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoSexoFnCadastro;
    private javax.swing.JMenu MnFnCadastroFile;
    private javax.swing.JMenuItem MnSair;
    private javax.swing.JRadioButton SexoFeminino;
    private javax.swing.JRadioButton SexoMasculino;
    private javax.swing.JButton btnFnCadastroCancelar;
    private javax.swing.JButton btnFnCadastroSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtFnCadastroCargo;
    private javax.swing.JPasswordField txtFnCadastroConfSenha;
    private javax.swing.JFormattedTextField txtFnCadastroCpf;
    private javax.swing.JTextField txtFnCadastroEmail;
    private javax.swing.JTextField txtFnCadastroLogin;
    private javax.swing.JTextField txtFnCadastroNome;
    private javax.swing.JFormattedTextField txtFnCadastroSalario;
    private javax.swing.JPasswordField txtFnCadastroSenha;
    private javax.swing.JFormattedTextField txtFnCadastroTelefone;
    // End of variables declaration//GEN-END:variables
}
