/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class ViewCliente extends javax.swing.JFrame {

    /**
     * Creates new form ViewClienteT
     */
    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClienteUsuario = new javax.swing.JTextField();
        txtClienteSenha = new javax.swing.JPasswordField();
        btnClienteAcessar = new javax.swing.JButton();
        btnClienteCadastra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnClienteFile = new javax.swing.JMenu();
        MnLogin = new javax.swing.JMenuItem();
        MnSair = new javax.swing.JMenuItem();
        MnClienteNavegador = new javax.swing.JMenu();
        MnClienteNavFuncionario = new javax.swing.JMenuItem();
        MnClienteSobre = new javax.swing.JMenu();
        MnClienteLoja = new javax.swing.JMenuItem();
        MnClienteCriadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo-icon.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login - Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Senha:");

        txtClienteUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteUsuarioFocusLost(evt);
            }
        });

        txtClienteSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteSenhaFocusLost(evt);
            }
        });

        btnClienteAcessar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnClienteAcessar.setText("Acessar");
        btnClienteAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAcessarActionPerformed(evt);
            }
        });

        btnClienteCadastra.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnClienteCadastra.setText("Cadastra-se");
        btnClienteCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCadastraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClienteCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClienteAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClienteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClienteUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClienteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        MnClienteFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-icon.png"))); // NOI18N
        MnClienteFile.setText("Arquivo");

        MnLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        MnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login-icon.png"))); // NOI18N
        MnLogin.setText("Login");
        MnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLoginActionPerformed(evt);
            }
        });
        MnClienteFile.add(MnLogin);

        MnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit-icon.png"))); // NOI18N
        MnSair.setText("Sair");
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        MnClienteFile.add(MnSair);

        jMenuBar1.add(MnClienteFile);

        MnClienteNavegador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/navegador-icon.png"))); // NOI18N
        MnClienteNavegador.setText("Navegador");

        MnClienteNavFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        MnClienteNavFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario-icon.png"))); // NOI18N
        MnClienteNavFuncionario.setText("Funcionário");
        MnClienteNavFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClienteNavFuncionarioActionPerformed(evt);
            }
        });
        MnClienteNavegador.add(MnClienteNavFuncionario);

        jMenuBar1.add(MnClienteNavegador);

        MnClienteSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/info-icon.png"))); // NOI18N
        MnClienteSobre.setText("Sobre");

        MnClienteLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loja-icon.png"))); // NOI18N
        MnClienteLoja.setText("Sobre a Loja");
        MnClienteSobre.add(MnClienteLoja);

        MnClienteCriadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/team-icon.png"))); // NOI18N
        MnClienteCriadores.setText("Sobre os Criadores");
        MnClienteCriadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClienteCriadoresActionPerformed(evt);
            }
        });
        MnClienteSobre.add(MnClienteCriadores);

        jMenuBar1.add(MnClienteSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLoginActionPerformed
        new ViewLogin().setVisible(true);
        ViewCliente.this.dispose();
    }//GEN-LAST:event_MnLoginActionPerformed

    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
        ViewCliente.this.dispose();
    }//GEN-LAST:event_MnSairActionPerformed

    private void MnClienteNavFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClienteNavFuncionarioActionPerformed
        new ViewFuncionario().setVisible(true);
        ViewCliente.this.dispose();
    }//GEN-LAST:event_MnClienteNavFuncionarioActionPerformed

    private void btnClienteCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCadastraActionPerformed
        new ViewClienteCadastra(null, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_btnClienteCadastraActionPerformed

    private void btnClienteAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAcessarActionPerformed
        if(txtClienteSenha.getText().equals("admin") && txtClienteUsuario.getText().equals("admin")) {
            JOptionPane.showMessageDialog(this, "Acessado Completo!");
        }
            /* Acesso para exemplo */
        if (txtClienteSenha.getText().equals("admin") && txtClienteUsuario.getText().equals("admin")) {
            new ViewClienteDesktop().setVisible(true);
            ViewCliente.this.dispose();
        }
        else {
            if (!txtClienteSenha.getText().equals("admin")) {
                JOptionPane.showMessageDialog(this, "Campo 'Senha' inválida");
                txtClienteSenha.setBackground(Color.red);
            }
            if (!txtClienteUsuario.getText().equals("admin")) {
                JOptionPane.showMessageDialog(this, "Campo 'Usuário' inválida");
                txtClienteUsuario.setBackground(Color.red);
            }
        }
    }//GEN-LAST:event_btnClienteAcessarActionPerformed

    private void txtClienteSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteSenhaFocusGained
        txtClienteSenha.setBackground(Color.white);
    }//GEN-LAST:event_txtClienteSenhaFocusGained

    private void txtClienteSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteSenhaFocusLost
        if(txtClienteSenha.getText().trim().equals("")) {
            txtClienteSenha.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtClienteSenhaFocusLost

    private void txtClienteUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteUsuarioFocusGained
        txtClienteUsuario.setBackground(Color.white);
    }//GEN-LAST:event_txtClienteUsuarioFocusGained

    private void txtClienteUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteUsuarioFocusLost
        if(txtClienteUsuario.getText().trim().equals("")) {
            txtClienteUsuario.setBackground(Color.red);
        }
    }//GEN-LAST:event_txtClienteUsuarioFocusLost

    private void MnClienteCriadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClienteCriadoresActionPerformed
        new ViewCriadores().setVisible(true);
    }//GEN-LAST:event_MnClienteCriadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnClienteCriadores;
    private javax.swing.JMenu MnClienteFile;
    private javax.swing.JMenuItem MnClienteLoja;
    private javax.swing.JMenuItem MnClienteNavFuncionario;
    private javax.swing.JMenu MnClienteNavegador;
    private javax.swing.JMenu MnClienteSobre;
    private javax.swing.JMenuItem MnLogin;
    private javax.swing.JMenuItem MnSair;
    private javax.swing.JButton btnClienteAcessar;
    private javax.swing.JButton btnClienteCadastra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClienteSenha;
    private javax.swing.JTextField txtClienteUsuario;
    // End of variables declaration//GEN-END:variables
}
